services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merge_crm
    ports:
      - "5432:5432"
    volumes:
      - merge_crm_db:/var/lib/postgresql/data

volumes:
  merge_crm_db:
